name: Build and Deploy Manually
on:
  push:
    branches:
      - "main"
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  build-and-deploy-manual:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Github ref is ${{ github.ref }}"
      - if: github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/')
        run: |
          echo "Deploy to TEST"
      - if: github.ref == 'refs/heads/main'
        run: |
          echo "Deploy to STAGING"
      - if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "Deploy to PRODUCTION"
      - run: |
          echo "done"
