name: Build and Deploy Manually
on:
  push:
    branches:
      - "main"
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
        target_environment:
          description: 'The target environment to deploy to'
          required: true
          default: 'Test' 
          type: choice
          options:
          - Test
jobs:
  build-and-deploy-manual:
    runs-on: ubuntu-latest
    steps:
      - name: Branch name
        run: echo Running on branch ${GITHUB_REF##*/}
      - run: |
          echo "Github ref is ${{ github.ref }}"
          echo "Target environment is ${{ github.event.inputs.target_environment }}"
      - if: github.event.inputs.target_environment == 'Test'
        run: |
          echo "Deploy to TEST"
      - if: github.ref == 'refs/heads/main' && github.event.inputs.target_environment == ''
        run: |
          echo "Deploy to STAGING"
      - if: startsWith(github.ref, 'refs/tags/') && github.event.inputs.target_environment == ''
        run: |
          echo "Deploy to PRODUCTION"
      - run: |
          echo "done"
