name: Build and Deploy Manually
on:
  push:
    branches:
      - "master"
    tags:
      - 'v*'
jobs:
  build-and-deploy-manual:
    runs-on: ubuntu-latest
    steps:
      - name: Branch name
        run: echo Running on branch ${GITHUB_REF##*/}
      - run: |
          echo "Github ref is ${{ github.ref }}"
          echo "Target environment is ${{ github.event.inputs.target_environment }}"
      - if: github.ref != 'refs/heads/main'
        run: |
          echo "Deploy to TEST"
      - if: github.ref == 'refs/heads/main'
        run: |
          echo "Deploy to STAGING"
      - if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "Deploy to PRODUCTION"
      - run: |
          echo "done"
